// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvnXcIZt-MkoA3c6qtaAhXapFLmLON20',
    appId: '1:540589264672:web:18d3b6e568fc3f7d0b5145',
    messagingSenderId: '540589264672',
    projectId: 'kiranasaathi-99e13',
    authDomain: 'kiranasaathi-99e13.firebaseapp.com',
    storageBucket: 'kiranasaathi-99e13.firebasestorage.app',
    measurementId: 'G-REN7P3NSB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCvnXcIZt-MkoA3c6qtaAhXapFLmLON20',
    appId: '1:540589264672:android:9d45155f340866030b5145', // Note: This is an assumption based on web appId pattern, ideally should match the one in google-services.json
    messagingSenderId: '540589264672',
    projectId: 'kiranasaathi-99e13',
    storageBucket: 'kiranasaathi-99e13.firebasestorage.app',
  );
}
